export const PRODUCT_LIST = "UI/PRODUCT/LIST"
export const PRODUCT_LIST_SUCCESS = "UI/PRODUCT/LIST/SUCCESS"
export const PRODUCT_LIST_ERROR = "UI/PRODUCT/LIST/ERROR"

export const PRODUCT_CREATE = "UI/PRODUCT/CREATE"
export const PRODUCT_CREATE_SUCCESS = "UI/PRODUCT/CREATE/SUCCESS"
export const PRODUCT_CREATE_ERROR = "UI/PRODUCT/CREATE/ERROR"

export const PRODUCT_SAVE = "UI/PRODUCT/SAVE"
export const PRODUCT_SAVE_SUCCESS = "UI/PRODUCT/SAVE/SUCCESS"
export const PRODUCT_SAVE_ERROR = "UI/PRODUCT/SAVE/ERROR"

export const PRODUCT_SHOW = "UI/PRODUCT/SHOW"
export const PRODUCT_SHOW_SUCCESS = "UI/PRODUCT/SHOW/SUCCESS"
export const PRODUCT_SHOW_ERROR = "UI/PRODUCT/SHOW/ERROR"

export const PRODUCT_EDIT = "UI/PRODUCT/EDIT"
export const PRODUCT_EDIT_SUCCESS = "UI/PRODUCT/EDIT/SUCCESS"
export const PRODUCT_EDIT_ERROR = "UI/PRODUCT/EDIT/ERROR"

export const PRODUCT_UPDATE = "UI/PRODUCT/UPDATE"
export const PRODUCT_UPDATE_SUCCESS = "UI/PRODUCT/UPDATE/SUCCESS"
export const PRODUCT_UPDATE_ERROR = "UI/PRODUCT/UPDATE/ERROR"

export const PRODUCT_DELETE = "UI/PRODUCT/DELETE"
export const PRODUCT_DELETE_SUCCESS = "UI/PRODUCT/DELETE/SUCCESS"
export const PRODUCT_DELETE_ERROR = "UI/PRODUCT/DELETE/ERROR"

export const PLAN_LIST = "UI/PLAN/LIST"
export const PLAN_LIST_SUCCESS = "UI/PLAN/LIST/SUCCESS"
export const PLAN_LIST_ERROR = "UI/PLAN/LIST/ERROR"

export const PLAN_CREATE = "UI/PLAN/CREATE"
export const PLAN_CREATE_SUCCESS = "UI/PLAN/CREATE/SUCCESS"
export const PLAN_CREATE_ERROR = "UI/PLAN/CREATE/ERROR"

export const PLAN_SAVE = "UI/PLAN/SAVE"
export const PLAN_SAVE_SUCCESS = "UI/PLAN/SAVE/SUCCESS"
export const PLAN_SAVE_ERROR = "UI/PLAN/SAVE/ERROR"

export const PLAN_SHOW = "UI/PLAN/SHOW"
export const PLAN_SHOW_SUCCESS = "UI/PLAN/SHOW/SUCCESS"
export const PLAN_SHOW_ERROR = "UI/PLAN/SHOW/ERROR"

export const PLAN_EDIT = "UI/PLAN/EDIT"
export const PLAN_EDIT_SUCCESS = "UI/PLAN/EDIT/SUCCESS"
export const PLAN_EDIT_ERROR = "UI/PLAN/EDIT/ERROR"

export const PLAN_UPDATE = "UI/PLAN/UPDATE"
export const PLAN_UPDATE_SUCCESS = "UI/PLAN/UPDATE/SUCCESS"
export const PLAN_UPDATE_ERROR = "UI/PLAN/UPDATE/ERROR"

export const PLAN_DELETE = "UI/PLAN/DELETE"
export const PLAN_DELETE_SUCCESS = "UI/PLAN/DELETE/SUCCESS"
export const PLAN_DELETE_ERROR = "UI/PLAN/DELETE/ERROR"

export const CHARGE_LIST = "UI/CHARGE/LIST"
export const CHARGE_LIST_SUCCESS = "UI/CHARGE/LIST/SUCCESS"
export const CHARGE_LIST_ERROR = "UI/CHARGE/LIST/ERROR"

export const CHARGE_CREATE = "UI/CHARGE/CREATE"
export const CHARGE_CREATE_SUCCESS = "UI/CHARGE/CREATE/SUCCESS"
export const CHARGE_CREATE_ERROR = "UI/CHARGE/CREATE/ERROR"

export const CHARGE_SAVE = "UI/CHARGE/SAVE"
export const CHARGE_SAVE_SUCCESS = "UI/CHARGE/SAVE/SUCCESS"
export const CHARGE_SAVE_ERROR = "UI/CHARGE/SAVE/ERROR"

export const CHARGE_SHOW = "UI/CHARGE/SHOW"
export const CHARGE_SHOW_SUCCESS = "UI/CHARGE/SHOW/SUCCESS"
export const CHARGE_SHOW_ERROR = "UI/CHARGE/SHOW/ERROR"

export const CHARGE_EDIT = "UI/CHARGE/EDIT"
export const CHARGE_EDIT_SUCCESS = "UI/CHARGE/EDIT/SUCCESS"
export const CHARGE_EDIT_ERROR = "UI/CHARGE/EDIT/ERROR"

export const CHARGE_UPDATE = "UI/CHARGE/UPDATE"
export const CHARGE_UPDATE_SUCCESS = "UI/CHARGE/UPDATE/SUCCESS"
export const CHARGE_UPDATE_ERROR = "UI/CHARGE/UPDATE/ERROR"

export const CHARGE_DELETE = "UI/CHARGE/DELETE"
export const CHARGE_DELETE_SUCCESS = "UI/CHARGE/DELETE/SUCCESS"
export const CHARGE_DELETE_ERROR = "UI/CHARGE/DELETE/ERROR"