export const PRODUCT_LIST = "UI/PRODUCT/LIST"
export const PRODUCT_LIST_SUCCESS = "UI/PRODUCT/LIST/SUCCESS"
export const PRODUCT_LIST_ERROR = "UI/PRODUCT/LIST/ERROR"

export const PRODUCT_CREATE = "UI/PRODUCT/CREATE"
export const PRODUCT_CREATE_SUCCESS = "UI/PRODUCT/CREATE/SUCCESS"
export const PRODUCT_CREATE_ERROR = "UI/PRODUCT/CREATE/ERROR"

export const PRODUCT_SAVE = "UI/PRODUCT/SAVE"
export const PRODUCT_SAVE_SUCCESS = "UI/PRODUCT/SAVE/SUCCESS"
export const PRODUCT_SAVE_ERROR = "UI/PRODUCT/SAVE/ERROR"

export const PRODUCT_SHOW = "UI/PRODUCT/SHOW"
export const PRODUCT_SHOW_SUCCESS = "UI/PRODUCT/SHOW/SUCCESS"
export const PRODUCT_SHOW_ERROR = "UI/PRODUCT/SHOW/ERROR"

export const PRODUCT_EDIT = "UI/PRODUCT/EDIT"
export const PRODUCT_EDIT_SUCCESS = "UI/PRODUCT/EDIT/SUCCESS"
export const PRODUCT_EDIT_ERROR = "UI/PRODUCT/EDIT/ERROR"

export const PRODUCT_UPDATE = "UI/PRODUCT/UPDATE"
export const PRODUCT_UPDATE_SUCCESS = "UI/PRODUCT/UPDATE/SUCCESS"
export const PRODUCT_UPDATE_ERROR = "UI/PRODUCT/UPDATE/ERROR"

export const PRODUCT_DELETE = "UI/PRODUCT/DELETE"
export const PRODUCT_DELETE_SUCCESS = "UI/PRODUCT/DELETE/SUCCESS"
export const PRODUCT_DELETE_ERROR = "UI/PRODUCT/DELETE/ERROR"